#!/usr/bin/env node
var program = require('commander')
var colors = require('colors')
var Marvel = require('./marvel.js')


program
  .version('0.1.0')
  .option('-f, --first100', 'Give me first 100 marvel characters')
  .parse(process.argv);

if (program.first100) {
  var marvel = new Marvel({
    publicKey : '3ffd0da969c4817bd34a1fb7219d0707',
    privateKey : '89bafbb9d7e4b778f536edd16e8a96ff74bb9508'
  })
  marvel.getFirst100()
}
